project_id = "ointmbbdqvfukluzknnh"

[functions.check-compliance-alerts]
verify_jwt = false

[functions.send-suspension-email]
verify_jwt = false

[functions.expire-empty-legs]
verify_jwt = false

[functions.send-driver-welcome-email]
verify_jwt = false
