-- Create countries table
CREATE TABLE public.countries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Anyone can view active countries" 
ON public.countries 
FOR SELECT 
USING (is_active = true);

CREATE POLICY "Admins can view all countries" 
ON public.countries 
FOR SELECT 
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update countries" 
ON public.countries 
FOR UPDATE 
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can insert countries" 
ON public.countries 
FOR INSERT 
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete countries" 
ON public.countries 
FOR DELETE 
USING (has_role(auth.uid(), 'admin'::app_role));

-- Create index for active countries
CREATE INDEX idx_countries_is_active ON public.countries(is_active);
CREATE INDEX idx_countries_code ON public.countries(code);

-- Insert all countries (only Kenya is active)
INSERT INTO public.countries (code, name, is_active) VALUES
('AF', 'Afghanistan', false),
('AL', 'Albania', false),
('DZ', 'Algeria', false),
('AD', 'Andorra', false),
('AO', 'Angola', false),
('AR', 'Argentina', false),
('AM', 'Armenia', false),
('AU', 'Australia', false),
('AT', 'Austria', false),
('AZ', 'Azerbaijan', false),
('BS', 'Bahamas', false),
('BH', 'Bahrain', false),
('BD', 'Bangladesh', false),
('BB', 'Barbados', false),
('BY', 'Belarus', false),
('BE', 'Belgium', false),
('BZ', 'Belize', false),
('BJ', 'Benin', false),
('BT', 'Bhutan', false),
('BO', 'Bolivia', false),
('BA', 'Bosnia and Herzegovina', false),
('BW', 'Botswana', false),
('BR', 'Brazil', false),
('BN', 'Brunei', false),
('BG', 'Bulgaria', false),
('BF', 'Burkina Faso', false),
('BI', 'Burundi', false),
('KH', 'Cambodia', false),
('CM', 'Cameroon', false),
('CA', 'Canada', false),
('CV', 'Cape Verde', false),
('CF', 'Central African Republic', false),
('TD', 'Chad', false),
('CL', 'Chile', false),
('CN', 'China', false),
('CO', 'Colombia', false),
('KM', 'Comoros', false),
('CG', 'Congo', false),
('CR', 'Costa Rica', false),
('HR', 'Croatia', false),
('CU', 'Cuba', false),
('CY', 'Cyprus', false),
('CZ', 'Czech Republic', false),
('CD', 'Democratic Republic of the Congo', false),
('DK', 'Denmark', false),
('DJ', 'Djibouti', false),
('DM', 'Dominica', false),
('DO', 'Dominican Republic', false),
('EC', 'Ecuador', false),
('EG', 'Egypt', false),
('SV', 'El Salvador', false),
('GQ', 'Equatorial Guinea', false),
('ER', 'Eritrea', false),
('EE', 'Estonia', false),
('ET', 'Ethiopia', false),
('FJ', 'Fiji', false),
('FI', 'Finland', false),
('FR', 'France', false),
('GA', 'Gabon', false),
('GM', 'Gambia', false),
('GE', 'Georgia', false),
('DE', 'Germany', false),
('GH', 'Ghana', false),
('GR', 'Greece', false),
('GD', 'Grenada', false),
('GT', 'Guatemala', false),
('GN', 'Guinea', false),
('GW', 'Guinea-Bissau', false),
('GY', 'Guyana', false),
('HT', 'Haiti', false),
('HN', 'Honduras', false),
('HU', 'Hungary', false),
('IS', 'Iceland', false),
('IN', 'India', false),
('ID', 'Indonesia', false),
('IR', 'Iran', false),
('IQ', 'Iraq', false),
('IE', 'Ireland', false),
('IL', 'Israel', false),
('IT', 'Italy', false),
('CI', 'Ivory Coast', false),
('JM', 'Jamaica', false),
('JP', 'Japan', false),
('JO', 'Jordan', false),
('KZ', 'Kazakhstan', false),
('KE', 'Kenya', true),
('KI', 'Kiribati', false),
('KW', 'Kuwait', false),
('KG', 'Kyrgyzstan', false),
('LA', 'Laos', false),
('LV', 'Latvia', false),
('LB', 'Lebanon', false),
('LS', 'Lesotho', false),
('LR', 'Liberia', false),
('LY', 'Libya', false),
('LI', 'Liechtenstein', false),
('LT', 'Lithuania', false),
('LU', 'Luxembourg', false),
('MK', 'Macedonia', false),
('MG', 'Madagascar', false),
('MW', 'Malawi', false),
('MY', 'Malaysia', false),
('MV', 'Maldives', false),
('ML', 'Mali', false),
('MT', 'Malta', false),
('MH', 'Marshall Islands', false),
('MR', 'Mauritania', false),
('MU', 'Mauritius', false),
('MX', 'Mexico', false),
('FM', 'Micronesia', false),
('MD', 'Moldova', false),
('MC', 'Monaco', false),
('MN', 'Mongolia', false),
('ME', 'Montenegro', false),
('MA', 'Morocco', false),
('MZ', 'Mozambique', false),
('MM', 'Myanmar', false),
('NA', 'Namibia', false),
('NR', 'Nauru', false),
('NP', 'Nepal', false),
('NL', 'Netherlands', false),
('NZ', 'New Zealand', false),
('NI', 'Nicaragua', false),
('NE', 'Niger', false),
('NG', 'Nigeria', false),
('KP', 'North Korea', false),
('NO', 'Norway', false),
('OM', 'Oman', false),
('PK', 'Pakistan', false),
('PW', 'Palau', false),
('PA', 'Panama', false),
('PG', 'Papua New Guinea', false),
('PY', 'Paraguay', false),
('PE', 'Peru', false),
('PH', 'Philippines', false),
('PL', 'Poland', false),
('PT', 'Portugal', false),
('QA', 'Qatar', false),
('RO', 'Romania', false),
('RU', 'Russia', false),
('RW', 'Rwanda', false),
('KN', 'Saint Kitts and Nevis', false),
('LC', 'Saint Lucia', false),
('VC', 'Saint Vincent and the Grenadines', false),
('WS', 'Samoa', false),
('SM', 'San Marino', false),
('ST', 'Sao Tome and Principe', false),
('SA', 'Saudi Arabia', false),
('SN', 'Senegal', false),
('RS', 'Serbia', false),
('SC', 'Seychelles', false),
('SL', 'Sierra Leone', false),
('SG', 'Singapore', false),
('SK', 'Slovakia', false),
('SI', 'Slovenia', false),
('SB', 'Solomon Islands', false),
('SO', 'Somalia', false),
('ZA', 'South Africa', false),
('KR', 'South Korea', false),
('SS', 'South Sudan', false),
('ES', 'Spain', false),
('LK', 'Sri Lanka', false),
('SD', 'Sudan', false),
('SR', 'Suriname', false),
('SZ', 'Swaziland', false),
('SE', 'Sweden', false),
('CH', 'Switzerland', false),
('SY', 'Syria', false),
('TW', 'Taiwan', false),
('TJ', 'Tajikistan', false),
('TZ', 'Tanzania', false),
('TH', 'Thailand', false),
('TL', 'Timor-Leste', false),
('TG', 'Togo', false),
('TO', 'Tonga', false),
('TT', 'Trinidad and Tobago', false),
('TN', 'Tunisia', false),
('TR', 'Turkey', false),
('TM', 'Turkmenistan', false),
('TV', 'Tuvalu', false),
('UG', 'Uganda', false),
('UA', 'Ukraine', false),
('AE', 'United Arab Emirates', false),
('GB', 'United Kingdom', false),
('US', 'United States', false),
('UY', 'Uruguay', false),
('UZ', 'Uzbekistan', false),
('VU', 'Vanuatu', false),
('VA', 'Vatican City', false),
('VE', 'Venezuela', false),
('VN', 'Vietnam', false),
('YE', 'Yemen', false),
('ZM', 'Zambia', false),
('ZW', 'Zimbabwe', false);